apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-test
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secret-store-test
    kind: ClusterSecretStore
  target:
    name: vault-secret
  data:
    - secretKey: vault-secret
      remoteRef:
        key: yyy/secrets/env
        property: password
