name: trivy

on:
  push:
    branches: 
      - main

jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Trivy
        run: |
          sudo apt-get install wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          
      - name: Run Trivy on first file
        run: trivy fs --exit-code=1 --scanners misconf --config-check ./namespaces/xxx/xxx-yaml-check.rego --namespaces user ./namespaces/xxx
      
      - name: Run Trivy on second file
        run: trivy fs --exit-code=1 --scanners misconf --config-check ./namespaces/yyy/yyy-yaml-check.rego --namespaces user ./namespaces/yyy
